# Generated by Django 4.1.2 on 2024-08-31 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_avatar_imagen_avatar_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='image',
            new_name='imagen',
        ),
    ]
