# Generated by Django 4.1.2 on 2024-08-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nombre',
            new_name='autor',
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
