# Generated by Django 4.1.2 on 2024-08-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_post_fecha_creacion_alter_post_posteo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
