# Generated by Django 4.1.2 on 2024-09-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
